/**
 * In-memory data store with seed data.
 * In production this would be replaced by a database.
 */

import { v4 as uuidv4 } from 'uuid';
import { Incident, Alert, MeshNode } from './models';

// ─── Mesh Nodes ───────────────────────────────────────────────────────────────

export const nodes: MeshNode[] = [
  {
    id: 'node-alpha',
    name: 'Node-Alpha',
    location: 'Downtown Command Center',
    status: 'ONLINE',
    ipAddress: '10.0.1.1',
    lastSeen: new Date().toISOString(),
    connectedPeers: 4,
    incidentsRelayed: 23,
  },
  {
    id: 'node-beta',
    name: 'Node-Beta',
    location: 'North District Hub',
    status: 'ONLINE',
    ipAddress: '10.0.1.2',
    lastSeen: new Date().toISOString(),
    connectedPeers: 3,
    incidentsRelayed: 17,
  },
  {
    id: 'node-gamma',
    name: 'Node-Gamma',
    location: 'East Industrial Zone',
    status: 'DEGRADED',
    ipAddress: '10.0.1.3',
    lastSeen: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    connectedPeers: 1,
    incidentsRelayed: 9,
  },
  {
    id: 'node-delta',
    name: 'Node-Delta',
    location: 'South Residential Area',
    status: 'ONLINE',
    ipAddress: '10.0.1.4',
    lastSeen: new Date().toISOString(),
    connectedPeers: 3,
    incidentsRelayed: 31,
  },
  {
    id: 'node-epsilon',
    name: 'Node-Epsilon',
    location: 'West Harbor Perimeter',
    status: 'ONLINE',
    ipAddress: '10.0.1.5',
    lastSeen: new Date().toISOString(),
    connectedPeers: 2,
    incidentsRelayed: 14,
  },
];

// ─── Helper: offset date ──────────────────────────────────────────────────────
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3600 * 1000).toISOString();
}

// ─── Seed Incidents ───────────────────────────────────────────────────────────

export const incidents: Incident[] = [
  {
    id: uuidv4(),
    title: 'Warehouse Fire - Building 7',
    description: 'Large blaze reported at East Industrial warehouse. Multiple fire crews dispatched. Smoke visible from 2km. Possible arson.',
    location: 'East Industrial Zone, Building 7',
    reporterName: 'Unit Echo-3',
    type: 'fire',
    severity: 'CRITICAL',
    status: 'in_progress',
    aiSummary: 'AI Analysis: Classified as a CRITICAL Fire/Smoke event. Arson indicators detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 96,
    createdAt: hoursAgo(2),
    updatedAt: hoursAgo(1),
  },
  {
    id: uuidv4(),
    title: 'Unauthorized Network Access - Server Farm',
    description: 'Cyber intrusion detected on primary server cluster. Ransomware signatures identified. Data breach suspected. Multiple systems compromised.',
    location: 'Downtown Command Center - IT Infrastructure',
    reporterName: 'SIEM-AutoAlert',
    type: 'cyber',
    severity: 'CRITICAL',
    status: 'in_progress',
    aiSummary: 'AI Analysis: Classified as a CRITICAL Cyber Security Threat. Ransomware and data breach patterns detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 99,
    createdAt: hoursAgo(3),
    updatedAt: hoursAgo(2),
  },
  {
    id: uuidv4(),
    title: 'Chemical Spill - Harbor Terminal',
    description: 'Toxic chemical leak reported near dock 4. Hazmat team en route. Evacuation of 200m radius underway.',
    location: 'West Harbor Perimeter, Dock 4',
    reporterName: 'Patrol-Unit-7',
    type: 'hazmat',
    severity: 'HIGH',
    status: 'in_progress',
    aiSummary: 'AI Analysis: Classified as a HIGH-priority Hazardous Materials Incident. Toxic chemical characteristics detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 84,
    createdAt: hoursAgo(4),
    updatedAt: hoursAgo(3),
  },
  {
    id: uuidv4(),
    title: 'Armed Intrusion - Residential Complex',
    description: 'Armed intruder reported breaching perimeter of Sunset Complex. Security breach confirmed via cameras. Suspect armed.',
    location: 'South Residential Area - Sunset Complex',
    reporterName: 'Resident-Camera-AI',
    type: 'intrusion',
    severity: 'CRITICAL',
    status: 'open',
    aiSummary: 'AI Analysis: Classified as a CRITICAL Security Intrusion. Armed breach indicators detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 97,
    createdAt: hoursAgo(0.5),
    updatedAt: hoursAgo(0.5),
  },
  {
    id: uuidv4(),
    title: 'Multi-Vehicle Collision - Highway 12',
    description: 'Significant traffic accident involving several vehicles on Highway 12 northbound. Injuries reported. Road blocked.',
    location: 'North District Hub - Highway 12',
    reporterName: 'Traffic-Cam-N4',
    type: 'traffic',
    severity: 'MEDIUM',
    status: 'in_progress',
    aiSummary: 'AI Analysis: Classified as a MEDIUM-priority Traffic/Vehicle Incident. Multi-vehicle collision with injuries detected. Immediate monitoring advised. Mesh relay active for real-time tracking.',
    riskScore: 46,
    createdAt: hoursAgo(5),
    updatedAt: hoursAgo(4),
  },
  {
    id: uuidv4(),
    title: 'Medical Emergency - Community Park',
    description: 'Cardiac event reported at North Community Park. Patient unresponsive. Bystander CPR in progress. Ambulance dispatched.',
    location: 'North District Hub - Community Park',
    reporterName: 'Citizen-Report',
    type: 'medical',
    severity: 'HIGH',
    status: 'in_progress',
    aiSummary: 'AI Analysis: Classified as a HIGH-priority Medical Emergency. Cardiac arrest indicators detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 74,
    createdAt: hoursAgo(1),
    updatedAt: hoursAgo(0.8),
  },
  {
    id: uuidv4(),
    title: 'Flood Warning - River District',
    description: 'River levels rising rapidly following storm. Flood warning issued for low-lying areas. Evacuation advisory in effect.',
    location: 'South Residential Area - River District',
    reporterName: 'Weather-Sensor-Grid',
    type: 'natural_disaster',
    severity: 'HIGH',
    status: 'open',
    aiSummary: 'AI Analysis: Classified as a HIGH-priority Natural Disaster Event. Flood/storm characteristics detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 87,
    createdAt: hoursAgo(6),
    updatedAt: hoursAgo(5),
  },
  {
    id: uuidv4(),
    title: 'Suspicious Package - Transit Hub',
    description: 'Unattended suspicious package reported at Central Transit Hub. Area cordoned off. Bomb disposal team notified.',
    location: 'Downtown Command Center - Transit Hub',
    reporterName: 'Security-Officer-12',
    type: 'hazmat',
    severity: 'HIGH',
    status: 'open',
    aiSummary: 'AI Analysis: Classified as a HIGH-priority Hazardous Materials Incident. Suspicious/unattended object indicators detected. Immediate emergency response recommended. Mesh relay active for real-time tracking.',
    riskScore: 82,
    createdAt: hoursAgo(0.3),
    updatedAt: hoursAgo(0.3),
  },
];

// ─── Seed Alerts (for HIGH/CRITICAL incidents) ────────────────────────────────

export const alerts: Alert[] = [
  {
    id: uuidv4(),
    incidentId: incidents[0].id,
    incidentTitle: incidents[0].title,
    type: 'fire',
    severity: 'CRITICAL',
    message: 'CRITICAL fire incident at East Industrial Zone. All fire units respond immediately. Evacuate 500m radius.',
    location: incidents[0].location,
    status: 'active',
    responderUnit: 'Fire-Brigade-Alpha',
    createdAt: incidents[0].createdAt,
  },
  {
    id: uuidv4(),
    incidentId: incidents[1].id,
    incidentTitle: incidents[1].title,
    type: 'cyber',
    severity: 'CRITICAL',
    message: 'CRITICAL cyber attack in progress. Isolate affected systems immediately. Activate incident response team.',
    location: incidents[1].location,
    status: 'acknowledged',
    responderUnit: 'Cyber-Response-Team',
    createdAt: incidents[1].createdAt,
    acknowledgedAt: hoursAgo(2.5),
  },
  {
    id: uuidv4(),
    incidentId: incidents[2].id,
    incidentTitle: incidents[2].title,
    type: 'hazmat',
    severity: 'HIGH',
    message: 'HIGH priority hazmat incident at West Harbor. HazMat-1 respond. Establish perimeter.',
    location: incidents[2].location,
    status: 'acknowledged',
    responderUnit: 'HazMat-Unit-1',
    createdAt: incidents[2].createdAt,
    acknowledgedAt: hoursAgo(3.5),
  },
  {
    id: uuidv4(),
    incidentId: incidents[3].id,
    incidentTitle: incidents[3].title,
    type: 'intrusion',
    severity: 'CRITICAL',
    message: 'CRITICAL armed intrusion. All patrol units to Sunset Complex. Approach with caution.',
    location: incidents[3].location,
    status: 'active',
    responderUnit: 'Police-Unit-7',
    createdAt: incidents[3].createdAt,
  },
  {
    id: uuidv4(),
    incidentId: incidents[5].id,
    incidentTitle: incidents[5].title,
    type: 'medical',
    severity: 'HIGH',
    message: 'HIGH priority medical emergency - cardiac arrest. Ambulance ETA 4 minutes. AED required.',
    location: incidents[5].location,
    status: 'active',
    responderUnit: 'Ambulance-Delta-2',
    createdAt: incidents[5].createdAt,
  },
  {
    id: uuidv4(),
    incidentId: incidents[6].id,
    incidentTitle: incidents[6].title,
    type: 'natural_disaster',
    severity: 'HIGH',
    message: 'HIGH priority flood warning. Emergency services on standby. Evacuation routes active.',
    location: incidents[6].location,
    status: 'active',
    responderUnit: 'Emergency-Management',
    createdAt: incidents[6].createdAt,
  },
  {
    id: uuidv4(),
    incidentId: incidents[7].id,
    incidentTitle: incidents[7].title,
    type: 'hazmat',
    severity: 'HIGH',
    message: 'HIGH priority suspicious package. Bomb disposal en route. Clear 200m radius.',
    location: incidents[7].location,
    status: 'active',
    responderUnit: 'Bomb-Disposal-Unit',
    createdAt: incidents[7].createdAt,
  },
];
