# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatch.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'dispatch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ispatch.proto\x12\x15sentinelmesh.dispatch\"\x91\x01\n\x10InterceptRequest\x12\x13\n\x0bincident_id\x18\x01 \x01(\t\x12\x14\n\x0cincident_lat\x18\x02 \x01(\x01\x12\x14\n\x0cincident_lon\x18\x03 \x01(\x01\x12\x12\n\nofficer_id\x18\x04 \x01(\t\x12\x13\n\x0bofficer_lat\x18\x05 \x01(\x01\x12\x13\n\x0bofficer_lon\x18\x06 \x01(\x01\"\x82\x01\n\x11InterceptResponse\x12\x13\n\x0bincident_id\x18\x01 \x01(\t\x12\x12\n\nofficer_id\x18\x02 \x01(\t\x12\x17\n\x0f\x64istance_meters\x18\x03 \x01(\x01\x12\x13\n\x0b\x65ta_seconds\x18\x04 \x01(\x05\x12\x16\n\x0eroute_polyline\x18\x05 \x01(\t2y\n\x0f\x44ispatchService\x12\x66\n\x11GetInterceptRoute\x12\'.sentinelmesh.dispatch.InterceptRequest\x1a(.sentinelmesh.dispatch.InterceptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTERCEPTREQUEST']._serialized_start=42
  _globals['_INTERCEPTREQUEST']._serialized_end=187
  _globals['_INTERCEPTRESPONSE']._serialized_start=190
  _globals['_INTERCEPTRESPONSE']._serialized_end=320
  _globals['_DISPATCHSERVICE']._serialized_start=322
  _globals['_DISPATCHSERVICE']._serialized_end=443
# @@protoc_insertion_point(module_scope)
